

services:
  db:
    image: postgres:18
    container_name: patient-service-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patientdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d patientdb"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
